### ISSUE TITLE
Cropping to improve Raspberry Pi FPS

### ISSUE THREAD

**Issue by leobrenes** [rangerdawavs/submarine-prototype#22]
**The raspberry code must be faster.** 
By cropping the image, the processing time can be reduced. The image should be cropped to a multiple of the vehicle radius. The coordinate system could break down with cropping so special care should be taken to prevent it. Every _n_ loops the entire frame should be scanned without cropping to prevent incorrect focusing on noise. In the rest of the loops, the cropped section should adjust to surround the previous center of the vehicle. A future addition could use the velocity data to improve the model

**Comment by rangerdawavs** [comment]
Tested raspberry pi fps:
To help determine the effectiveness on cropping the image, some quick tests on the base code have been run.
Test 1:
Base code from patch 1 with the addition of two lines of code that function as a timer, also the lines of print() have been turned off
Bluetooth off
Execution:
Waited 10 mins with raspberry off to ensure it was cooled down, turned on, opened code, waited for raspberry CPU usage to stabilize around 0%, started python code.
Results: time between loops stabilized at around 0.023 seconds when background was static, stabilized to 0.026 when background was moving, although approximately once per second, for 2-3 loops, the time will jump to 0.042, I don't know what could be the cause of it. When about half of the mask changed (big background change, probably will never happen) time would spike to 0.5.
CPU usage stayed constant at around 26%
Test 2
Base code from patch1, bluetooth off, extra code for timer, set if statement that checks for the amount of countouts to false, as such, the code should never show the contours or calculate any variables.
Execution: identical to test1
Results: time between loops stabilized to 0.017, although approximately once per second, for 2-3 loops, the time will jump to 0.026, I don't know what could be the cause of it.
CPU usage stays constant at around 23%
Test 3
Basic code same as test 2, but commented the code that calculates the countouts, so it should only take photos and show them.
Execution: same as test1
Results: time per loop stabilizes at 0.008, no jumps in performance registered
CPU stabilizes at 20%
Conclusion:
Apparently the base video recording has a delay of 8 milliseconds, while calculating the countours accounts for about 9 milliseconds, and the rest of the operations acount for about 10 milliseconds.
I'm worried about the random spikes, although I don't know what causes them, as it could cause problems when trying to calibrate the time necessary for sending info over bluetooth.

**Comment by leobrenes** [comment]
A fourth test could be conducted that only prints the data of the loops that take longer than the stabilized duration for test 1 and 2. With the addition of a timer between "spike loops" a pattern between these outlier durations could be found. These loops  could have a constant separation or print position information that does not match the rest of the data. This could help us narrow down the source. @rangerdawavs
